#pragma once

#include "mx.h"

enum mx::EStreamError
{
	UNKNOWN_STREAM_ERROR,

	STREAM_ERROR_UNKNOWN_DEVICE_TYPE,

	STREAM_ERROR_INVALID_PREPARE_SIGNATURE_FOR_DEVICE_TYPE,

	STREAM_ERROR_EMPTY_FILE_PATH,
	
	STREAM_ERROR_FILE_ALREADY_OPEN,
	STREAM_ERROR_FILE_NOT_OPEN,

	STREAM_ERROR_FILE_GET_SEEK,
	STREAM_ERROR_FILE_SET_SEEK,
	STREAM_ERROR_FILE_READ,
	STREAM_ERROR_FILE_WRITE,
	STREAM_ERROR_FILE_FLUSH,
	STREAM_ERROR_FILE_OPEN,
	STREAM_ERROR_FILE_CLOSE
};