#pragma once

#include "mx.h"

enum mx::EStreamError
{
	STREAM_ERROR_UNKNOWN,

	STREAM_ERROR_UNKNOWN_DEVICE_TYPE,

	STREAM_ERROR_INVALID_PREPARE_SIGNATURE_FOR_DEVICE_TYPE,

	STREAM_ERROR_FILE_ALREADY_OPEN,
	STREAM_ERROR_FILE_NOT_OPEN,

	STREAM_ERROR_EMPTY_FILE_PATH
};