#pragma once

#include "mx.h"

enum mx::EBMPFileType
{
	UNKNOWN_BMP_FILE_TYPE,

	BMP_FILE_TYPE_WINDOWS,
	BMP_FILE_TYPE_OS2,
	BMP_FILE_TYPE_COLOUR_ICON,
	BMP_FILE_TYPE_COLOUR_POINTER,
	BMP_FILE_TYPE_STRUCT_ICON,
	BMP_FILE_TYPE_POINTER
};