#pragma once

#include "mx.h"

enum mx::EBMPDIBHeader
{
	UNKNOWN_BMP_DIB_HEADER,

	BMP_DIB_HEADER_BITMAPCOREHEADER,
	BMP_DIB_HEADER_OS21XBITMAPHEADER,
	BMP_DIB_HEADER_OS22XBITMAPHEADER_64,
	BMP_DIB_HEADER_OS22XBITMAPHEADER_16,
	BMP_DIB_HEADER_BITMAPINFOHEADER,
	BMP_DIB_HEADER_BITMAPV2INFOHEADER,
	BMP_DIB_HEADER_BITMAPV3INFOHEADER,
	BMP_DIB_HEADER_BITMAPV4HEADER,
	BMP_DIB_HEADER_BITMAPV5HEADER
};