#pragma once

#include "mx.h"

enum mx::EBMPCompressionType
{
	UNKNOWN_BMP_COMPRESSION_TYPE = 0xFF,

	BMP_COMPRESSION_RGB = 0,
	BMP_COMPRESSION_RLE8 = 1,
	BMP_COMPRESSION_RLE4 = 2,
	BMP_COMPRESSION_BITFIELDS = 3,
	BMP_COMPRESSION_JPEG = 4,
	BMP_COMPRESSION_PNG = 5,
	BMP_COMPRESSION_ALPHABITFIELDS = 6,
	BMP_COMPRESSION_CMYK = 11,
	BMP_COMPRESSION_CMYKRLE8 = 12,
	BMP_COMPRESSION_CMYKRLE4 = 13
};