#pragma once

#include "mx.h"

enum mx::EVersionedOperatingSystem
{
	VERSIONED_OPERATING_SYSTEM_UNKNOWN,

	VERSIONED_OPERATING_SYSTEM_WINDOWS_XP,
	VERSIONED_OPERATING_SYSTEM_WINDOWS_VISTA,
	VERSIONED_OPERATING_SYSTEM_WINDOWS_7,
	VERSIONED_OPERATING_SYSTEM_WINDOWS_8,
	VERSIONED_OPERATING_SYSTEM_WINDOWS_8_1,
	VERSIONED_OPERATING_SYSTEM_WINDOWS_10,

	VERSIONED_OPERATING_SYSTEM_LINUX,

	VERSIONED_OPERATING_SYSTEM_MAC
};