#pragma once

#include "mx.h"

enum mx::EVersionedPlatform
{
	VERSIONED_PLATFORM_UNKNOWN,

	VERSIONED_PLATFORM_PC,

	VERSIONED_PLATFORM_PLAY_STATION_1,
	VERSIONED_PLATFORM_PLAY_STATION_2,
	VERSIONED_PLATFORM_PLAY_STATION_3,
	VERSIONED_PLATFORM_PLAY_STATION_4,

	VERSIONED_PLATFORM_XBOX_ORIGINAL,
	VERSIONED_PLATFORM_XBOX_360,
	VERSIONED_PLATFORM_XBOX_ONE,

	VERSIONED_PLATFORM_GAME_CUBE,

	VERSIONED_PLATFORM_WII
};