#pragma once

#include "mx.h"

enum mx::EVersionedGraphicsLibrary
{
	VERSIONED_GRAPHICS_LIBRARY_UNKNOWN,

	VERSIONED_GRAPHICS_LIBRARY_OPEN_GL_3_3,
	VERSIONED_GRAPHICS_LIBRARY_OPEN_GL_4_6,

	VERSIONED_GRAPHICS_LIBRARY_DIRECT_X_8,
	VERSIONED_GRAPHICS_LIBRARY_DIRECT_X_9,
	VERSIONED_GRAPHICS_LIBRARY_DIRECT_X_10,
	VERSIONED_GRAPHICS_LIBRARY_DIRECT_X_11,
	VERSIONED_GRAPHICS_LIBRARY_DIRECT_X_12
};